query GetSneakers($sortFilter: JSON, $perPage: Int, $page: Int) {
  ReleasePagination(sort: $sortFilter, perPage: $perPage, page: $page) {
    count
    pageInfo {
      currentPage
      pageCount
      hasNextPage
    }
    items {
      _id
      title
      description
      date
      colorway
      price
      brand {
        title
      }
      catalog {
        name
      }
      raffleLinks {
        raffleId
        link
      }
      raffles {
        link
        raffleWebsite {
          name
          logo
        }
      }
      nickname
      imageUrls
      resellUrls
      resellsizes {
        uri
        lowPrice
        highPrice
        currencyUnit
        sizeType
        sizes {
          size
          price
        }
      }
      buyLinks {
        title
        link
      }
    }
  }
}
